name = "kirsi-rohbock-portfolio"
compatibility_date = "2024-06-30"

[build]
command = "npm run build"
cwd = "."

[[pages_build_output_dir]]
output_dir = "dist/public"

[env.production.vars]
NODE_ENV = "production"

[env.production.secrets]
DATABASE_URL = "your-database-url"
OPENAI_API_KEY = "your-openai-api-key"